from setuptools import setup, find_packages

setup(
    name='stable-audio-tools',
    version='0.0.16',
    url='https://github.com/Stability-AI/stable-audio-tools.git',
    author='Stability AI',
    description='Training and inference tools for generative audio models from Stability AI',
    packages=find_packages(),  
    install_requires=[
        'aeiou',
        'alias-free-torch',
        'auraloss',
        'descript-audio-codec',
        'einops',
        'einops-exts',
        'ema-pytorch',
        'encodec',
        'gradio',
        'huggingface_hub',
        'importlib-resources',
        'k-diffusion',
        'laion-clap',
        'local-attention',
        'pandas',
        'pedalboard',
        'prefigure',
        'pytorch_lightning', 
        'PyWavelets',
        'safetensors',
        'sentencepiece',
        's3fs',
        'torch',
        'torchaudio',
        'torchmetrics',
        'tqdm',
        'transformers',
        'v-diffusion-pytorch',
        'vector-quantize-pytorch',
        'wandb',
        'webdataset',
        'x-transformers'
    ],
)